import * as React from "react";
import "./text-box-group-style.scss";
export interface TextBoxGroupProps {
    autoComplete?: "on" | "off";
    className?: string;
    disabled?: boolean;
    error?: string;
    focus?: boolean;
    id?: string;
    label?: string;
    leftIcon?: React.ReactNode;
    leftText?: string;
    leftTitle?: string;
    maxLength?: number;
    minLength?: number;
    name: string;
    onBlur?: (event: React.FocusEvent<HTMLInputElement>) => void;
    onChange: (event: React.ChangeEvent<HTMLInputElement>) => void;
    onFocus?: (event: React.FocusEvent<HTMLInputElement>) => void;
    onKeyDown?: (event: React.KeyboardEvent<HTMLInputElement>) => void;
    onKeyPress?: (event: React.KeyboardEvent<HTMLInputElement>) => void;
    onKeyUp?: (event: React.KeyboardEvent<HTMLInputElement>) => void;
    onLeftClick?: (event: React.MouseEvent<HTMLDivElement>) => void;
    onRightClick?: (event: React.MouseEvent<HTMLDivElement>) => void;
    pattern?: string;
    placeholder?: string;
    readOnly?: boolean;
    reference?: React.RefObject<HTMLInputElement>;
    required?: boolean;
    rightIcon?: React.ReactNode;
    rightText?: string;
    rightTitle?: string;
    type?: string;
    value: string | number;
    success?: boolean;
    showErrorMessage?: boolean;
}
export declare const TextBoxGroup: React.FunctionComponent<TextBoxGroupProps>;
